import { useState } from 'react'
import type { DoctorPacket as DoctorPacketType } from '../api/types'

interface DoctorPacketProps {
  packet: DoctorPacketType
}

export default function DoctorPacket({ packet }: DoctorPacketProps) {
  const [copied, setCopied] = useState(false)

  const escapeHtml = (value: string) =>
    value
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;')

  const formatPacketText = () => {
    const lines = [
      '=== PRE-VISIT SYMPTOM SUMMARY ===',
      '',
      'HISTORY OF PRESENT ILLNESS:',
      packet.hpi,
      '',
      ...(packet.system_longitudinal_flags?.length ? [
        'LONGITUDINAL SYSTEM FLAGS:',
        ...packet.system_longitudinal_flags.map(f => `  ⚠ ${f}`),
        '',
      ] : []),
      'PERTINENT POSITIVES:',
      ...packet.pertinent_positives.map(p => `  - ${p}`),
      '',
      'PERTINENT NEGATIVES:',
      packet.pertinent_negatives.length
        ? packet.pertinent_negatives.map(n => `  - ${n}`).join('\n')
        : '  (None noted)',
      '',
      'TIMELINE:',
      ...packet.timeline_bullets.map(b => `  - ${b}`),
      '',
      'PATIENT CONCERNS:',
      ...packet.questions_for_clinician.map(q => `  - ${q}`),
      '',
      '---',
      'Generated by SymptomPal (Demonstration Only)',
    ]
    return lines.join('\n')
  }

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(formatPacketText())
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy:', err)
    }
  }

  const handlePrint = () => {
    const printWindow = window.open('', '_blank')
    if (printWindow) {
      const escaped = {
        hpi: escapeHtml(packet.hpi),
        flags: packet.system_longitudinal_flags?.length
          ? packet.system_longitudinal_flags.map(f => `<li>${escapeHtml(f)}</li>`).join('')
          : '',
        positives: packet.pertinent_positives.map(p => `<li>${escapeHtml(p)}</li>`).join(''),
        negatives: packet.pertinent_negatives.length
          ? packet.pertinent_negatives.map(n => `<li>${escapeHtml(n)}</li>`).join('')
          : '<li><em>None noted</em></li>',
        timeline: packet.timeline_bullets.map(b => `<li>${escapeHtml(b)}</li>`).join(''),
        questions: packet.questions_for_clinician.map(q => `<li>${escapeHtml(q)}</li>`).join(''),
      }
      printWindow.document.write(`
        <html>
          <head>
            <title>Pre-Visit Symptom Summary</title>
            <style>
              body { font-family: system-ui, sans-serif; padding: 20px; line-height: 1.6; }
              h1 { font-size: 18px; border-bottom: 2px solid #333; padding-bottom: 8px; }
              h2 { font-size: 14px; color: #555; margin-top: 16px; margin-bottom: 8px; }
              ul { margin: 0; padding-left: 20px; }
              li { margin: 4px 0; }
              .disclaimer { font-size: 11px; color: #888; margin-top: 24px; border-top: 1px solid #ddd; padding-top: 12px; }
            </style>
          </head>
          <body>
            <h1>Pre-Visit Symptom Summary</h1>
            <h2>History of Present Illness</h2>
            <p>${escaped.hpi}</p>
            ${escaped.flags ? `<h2 style="color: #b45309;">⚠ Longitudinal System Flags</h2><ul>${escaped.flags}</ul>` : ''}
            <h2>Pertinent Positives</h2>
            <ul>${escaped.positives}</ul>
            <h2>Pertinent Negatives</h2>
            <ul>${escaped.negatives}</ul>
            <h2>Timeline</h2>
            <ul>${escaped.timeline}</ul>
            <h2>Patient Concerns</h2>
            <ul>${escaped.questions}</ul>
            <div class="disclaimer">Generated by SymptomPal - Demonstration Only, Not Medical Advice</div>
          </body>
        </html>
      `)
      printWindow.document.close()
      printWindow.print()
    }
  }

  return (
    <div className="bg-white rounded-xl shadow-md p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-gray-800">Doctor Packet</h3>
        <div className="flex space-x-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1 text-sm bg-gray-100 hover:bg-gray-200 rounded-md transition-colors"
          >
            {copied ? 'Copied!' : 'Copy'}
          </button>
          <button
            onClick={handlePrint}
            className="px-3 py-1 text-sm bg-blue-100 text-blue-700 hover:bg-blue-200 rounded-md transition-colors"
          >
            Print
          </button>
        </div>
      </div>

      <div className="space-y-4 text-sm">
        {/* HPI */}
        <div>
          <h4 className="font-medium text-gray-700 mb-1">History of Present Illness</h4>
          <p className="text-gray-800 bg-gray-50 p-3 rounded-lg">{packet.hpi}</p>
        </div>

        {/* Longitudinal System Flags */}
        {packet.system_longitudinal_flags && packet.system_longitudinal_flags.length > 0 && (
          <div>
            <h4 className="font-medium text-amber-700 mb-1 flex items-center gap-1.5">
              <span className="w-2 h-2 bg-amber-500 rounded-full" />
              Longitudinal System Flags
            </h4>
            <div className="bg-amber-50 border border-amber-200 p-3 rounded-lg">
              <ul className="list-disc list-inside text-amber-900">
                {packet.system_longitudinal_flags.map((flag, i) => (
                  <li key={i}>{flag}</li>
                ))}
              </ul>
            </div>
          </div>
        )}

        {/* Pertinent Positives */}
        <div>
          <h4 className="font-medium text-gray-700 mb-1">Pertinent Positives</h4>
          <ul className="list-disc list-inside text-gray-800 bg-gray-50 p-3 rounded-lg">
            {packet.pertinent_positives.map((p, i) => (
              <li key={i}>{p}</li>
            ))}
          </ul>
        </div>

        {/* Pertinent Negatives */}
        {packet.pertinent_negatives.length > 0 && (
          <div>
            <h4 className="font-medium text-gray-700 mb-1">Pertinent Negatives</h4>
            <ul className="list-disc list-inside text-gray-800 bg-gray-50 p-3 rounded-lg">
              {packet.pertinent_negatives.map((n, i) => (
                <li key={i}>{n}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Timeline */}
        <div>
          <h4 className="font-medium text-gray-700 mb-1">Timeline</h4>
          <ul className="list-disc list-inside text-gray-800 bg-gray-50 p-3 rounded-lg">
            {packet.timeline_bullets.map((b, i) => (
              <li key={i}>{b}</li>
            ))}
          </ul>
        </div>

        {/* Questions */}
        <div>
          <h4 className="font-medium text-gray-700 mb-1">Patient Concerns</h4>
          <p className="text-xs text-gray-400 mb-2">Inferred from conversation patterns</p>
          <ul className="list-disc list-inside text-gray-800 bg-gray-50 p-3 rounded-lg">
            {packet.questions_for_clinician.map((q, i) => (
              <li key={i}>{q}</li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
